In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
X, y = make_classification(n_samples=10000, n_features=20, n_classes=2)

In [3]:
X.shape,y.shape

((10000, 20), (10000,))

In [4]:
print (X[:10, :5])

[[-0.72943958 -0.74399627  0.35945122  0.17219222 -1.03447141]
 [-0.66104152 -0.83761617 -1.77361377  1.27618609  0.51456643]
 [ 1.91584036 -1.79357522 -1.57752946  0.16010251  0.93307039]
 [ 1.46705712 -0.20893358 -1.15149326 -0.4253336   0.20725987]
 [ 1.43132311 -1.40623378 -1.61157522 -0.44567197  0.65432707]
 [ 0.48348643  0.53677046 -0.58926871  0.13655635 -0.53974318]
 [-2.20515693 -0.26127767  2.4122683   1.83202805 -0.23348706]
 [ 0.19920287 -0.91659317  0.78072623 -0.92003394 -1.37985768]
 [ 0.67410368 -0.99896253  0.89436524  0.29896247 -0.2537148 ]
 [-1.54695154  1.17008447  1.76482219  1.54514157 -0.38537206]]


In [5]:
print (y[:5])

[0 0 0 1 1]


In [6]:
minmaxsc = MinMaxScaler()

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size = 0.33)

In [8]:
X_train 

array([[-0.31419265, -0.17128105, 0.42245146, ..., 2.10913833,
 0.35538378, 0.13292289],
 [ 1.89465455, 0.17137708, 1.49317562, ..., -0.15489096,
 -2.13686667, 2.85787506],
 [-0.57940526, -0.23483075, -2.01692848, ..., -1.94019297,
 0.18891223, -2.28705783],
 ...,
 [-1.34506553, 0.46281581, -1.09212435, ..., 0.58265427,
 -0.06122451, -2.05793408],
 [-0.64379547, 0.2304502 , -1.68811375, ..., -0.4052049 ,
 0.9904773 , -2.04043319],
 [-3.4050277 , -1.34857326, -0.46046403, ..., -0.89605177,
 -0.88289295, -3.12280651]])

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6700, 20), (3300, 20), (6700,), (3300,))

In [10]:
minmaxsc.fit(X_train)

MinMaxScaler()

In [11]:
minmaxsc.transform(X_train)
minmaxsc.transform(X_test)

array([[0.63723895, 0.43043021, 0.25908913, ..., 0.53648523, 0.36761289,
 0.38682895],
 [0.53165348, 0.57232507, 0.17501845, ..., 0.65399234, 0.48021521,
 0.23876896],
 [0.50107266, 0.74924813, 0.19832326, ..., 0.4644589 , 0.49099525,
 0.23284821],
 ...,
 [0.52446343, 0.38594599, 0.28915136, ..., 0.63765499, 0.42535698,
 0.32165167],
 [0.3482073 , 0.50724072, 0.4094101 , ..., 0.43380729, 0.50731082,
 0.27662041],
 [0.77707465, 0.46721365, 0.23106677, ..., 0.54307506, 0.61248841,
 0.4748224 ]])

In [12]:
model =  RandomForestClassifier()

In [13]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [14]:
y_pred = model.predict(X_test)

In [15]:
y_pred.shape

(3300,)

In [16]:
y_pred[:10]

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [17]:
type(y_pred[0])

numpy.int64

In [18]:
y_pr=1.0*y_pred

In [19]:
type(y_pr[0])

numpy.float64

In [20]:
y_te=1.0*y_test

In [21]:
type(y_te[0])

numpy.float64

In [22]:
y_pr=y_pred.astype("float64")

In [23]:
np.mean(y_pr),np.std(y_pr)

(0.51, 0.4998999899979995)

In [24]:
np.mean(y_te),np.std(y_te)

(0.5021212121212121, 0.4999955004388908)

In [25]:
np.corrcoef(y_te,y_pr)

array([[1. , 0.84857737],
 [0.84857737, 1. ]])

In [26]:
mb = confusion_matrix(y_test, y_pred)

In [27]:
mb

array([[1505, 138],
 [ 112, 1545]])

In [28]:
# "https://www.stackvidhya.com/plot-confusion-matrix-in-python-and-why/"