In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
X, y = make_classification(n_samples = 10000, n_features = 20, n_classes = 2)

In [3]:
X.shape, y.shape

((10000, 20), (10000,))

In [5]:
print(y[:10])

[0 1 1 1 0 1 0 1 1 1]


In [6]:
minmaxcs = MinMaxScaler()

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((7000, 20), (3000, 20), (7000,), (3000,))

In [10]:
X_train

array([[ 0.14011196, -2.58445854, 0.61550055, ..., -1.20148264,
 0.60024368, 0.51375752],
 [ 0.53619644, 0.17064316, -1.8992461 , ..., -1.56676703,
 -0.66571333, -0.39182243],
 [-0.45291097, 1.65151991, 1.18192891, ..., -0.95921506,
 0.07383697, 1.80272547],
 ...,
 [ 0.55345652, -0.08474506, 0.97128436, ..., 0.34903381,
 1.03080012, 0.42128445],
 [-0.74575666, -1.18812237, 0.85616438, ..., 0.92106882,
 2.09919077, -0.00359408],
 [-0.80194846, -0.81236047, -1.34267409, ..., 0.3504485 ,
 1.72784299, -1.46812219]])

In [11]:
X_test

array([[ 1.50891076e-03, 3.65523498e-01, -5.48164279e-01, ...,
 -1.02046076e+00, 6.23986065e-01, 2.15123307e+00],
 [ 3.71351899e-01, -1.19868195e+00, -6.07061107e-01, ...,
 -6.32413009e-01, 1.03292758e+00, 8.19998928e-01],
 [-2.30041632e-01, 1.31473411e+00, -1.25701883e+00, ...,
 3.40323041e-01, -9.60173443e-01, -1.24646269e+00],
 ...,
 [ 2.58621999e+00, -9.27684190e-01, -6.71105981e-01, ...,
 2.12043052e-01, -1.00537540e+00, -1.27462951e+00],
 [-6.65796208e-01, 6.01763014e-01, 2.15849534e-01, ...,
 -3.20437515e-01, 1.04594859e+00, -7.29167388e-01],
 [-1.44588421e+00, -4.56867154e-01, -1.75299705e+00, ...,
 1.07516150e+00, -1.05903392e+00, 1.42673700e+00]])

In [12]:
model = RandomForestClassifier()

In [13]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred.shape

(3000,)

In [18]:
y_pr, y_te = 1.0*y_pred, 1.0*y_test

In [19]:
np.mean(y_pr), np.mean(y_te)

(0.48733333333333334, 0.49333333333333335)

In [20]:
np.corrcoef(y_te, y_pr)

array([[1. , 0.97206058],
 [0.97206058, 1. ]])

In [21]:
confm = confusion_matrix(y_test, y_pred)
print(confm)

[[1508   12]
 [  30 1450]]
