## Numpy lab - w3
### Link: https://www.w3resource.com/python-exercises/numpy/basic/index.php

### Ex. 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [3]:
import numpy as np

a = np.array([1, 3, np.nan, np.inf])
np.isfinite(a)

array([ True, True, False, False])

### Ex. 11.Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [4]:
a_array = np.random.rand(1, 5)
b_array = np.random.rand(1, 5)
print(a_array)
print(b_array)

print(np.equal(a_array, b_array))

a_array = np.array([1, 2, 3, 4, 5])
b_array = np.array([1., 2., 3., 4., 5.0001])

print(np.equal(a_array, b_array))
print(np.allclose(a_array, b_array))

[[0.88500578 0.66581243 0.63045277 0.54359249 0.83209624]]
[[0.3919436  0.99322047 0.54415996 0.29706467 0.88430643]]
[[False False False False False]]
[ True  True  True  True False]
False


### Ex. 17 Write a NumPy program to generate a random number between 0 and 1.

In [5]:
zero_to_one_array = np.random.rand(7)
zero_to_one_array

array([0.10701413, 0.9358542 , 0.28330123, 0.76675963, 0.88198998,
 0.32512635, 0.73751078])

In [6]:
zero_to_ten_array = np.random.randint(0, 11, 5)
zero_to_ten_array

array([ 3, 10, 3, 9, 5])

### Ex. 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [7]:
zero_to_ten_int_array = np.random.randint(1, 11, 5)
print(zero_to_ten_int_array)

[5 5 6 5 5]


### Ex. 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [8]:
zeros_md_numbers = np.diag(range(1,6))
zeros_md_numbers

array([[1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]])

### Ex. 35. Write a NumPy program to save a given array to a binary file 

In [14]:
random_array = np.random.randint(1, 11, (5,5))
print('Random array\n', random_array)

Random array
 [[ 1  8 10  4  3]
 [ 4 10  3  7  5]
 [ 8  8  9  8 10]
 [ 1  1  8  8  5]
 [ 2  8  6 10  6]]


In [15]:
from tempfile import TemporaryFile
tempFile = TemporaryFile()
np.save(tempFile, random_array)

In [18]:
_ = tempFile.seek(0)
np.load(tempFile)

array([[ 1, 8, 10, 4, 3],
 [ 4, 10, 3, 7, 5],
 [ 8, 8, 9, 8, 10],
 [ 1, 1, 8, 8, 5],
 [ 2, 8, 6, 10, 6]])